-- 修复 Supabase 权限问题

-- 1. 禁用所有表的 RLS（行级安全）
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE diary DISABLE ROW LEVEL SECURITY;
ALTER TABLE wishes DISABLE ROW LEVEL SECURITY;
ALTER TABLE moods DISABLE ROW LEVEL SECURITY;
ALTER TABLE checkin DISABLE ROW LEVEL SECURITY;
ALTER TABLE water DISABLE ROW LEVEL SECURITY;
ALTER TABLE drawings DISABLE ROW LEVEL SECURITY;
ALTER TABLE photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE coupons DISABLE ROW LEVEL SECURITY;
ALTER TABLE intimacy DISABLE ROW LEVEL SECURITY;
ALTER TABLE capsules DISABLE ROW LEVEL SECURITY;
ALTER TABLE secrets DISABLE ROW LEVEL SECURITY;
ALTER TABLE pet DISABLE ROW LEVEL SECURITY;
ALTER TABLE playlist DISABLE ROW LEVEL SECURITY;

-- 2. 给 anon 角色授权
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon;

-- 3. 验证权限
SELECT * FROM messages LIMIT 1;
